create extension if not exists citext;

create table if not exists public.allowed_users (
  id uuid primary key default gen_random_uuid(),
  email citext not null unique,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.allowed_users enable row level security;

drop policy if exists "allowed_users_select_own_email" on public.allowed_users;

create policy "allowed_users_select_own_email"
on public.allowed_users
for select
to authenticated
using (
  lower(email::text) = lower(coalesce((auth.jwt() ->> 'email'), ''))
);

comment on table public.allowed_users is
'Application allowlist for Beyond Ink POS Google-authenticated users.';

create table if not exists public.services (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  base_price numeric(12, 2) not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.add_ons (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  default_price numeric(12, 2) not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.inventory_items (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  sku text unique,
  unit text not null,
  stock_quantity numeric(12, 2) not null default 0,
  reorder_level numeric(12, 2) not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.service_material_prices (
  id uuid primary key default gen_random_uuid(),
  service_id uuid not null references public.services(id) on delete cascade,
  inventory_item_id uuid not null references public.inventory_items(id) on delete cascade,
  unit_price numeric(12, 2) not null check (unit_price >= 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (service_id, inventory_item_id)
);

create table if not exists public.sales_transactions (
  id uuid primary key default gen_random_uuid(),
  transaction_number bigint generated by default as identity unique,
  cashier_name text not null,
  status text not null default 'draft' check (status in ('draft', 'completed', 'cancelled')),
  delivery_enabled boolean not null default false,
  delivery_customer_name text,
  delivery_address text,
  delivery_drop_off_location text,
  delivery_fee numeric(12, 2) not null default 0 check (delivery_fee >= 0),
  discount_type text check (discount_type in ('fixed', 'percentage')),
  discount_value numeric(12, 2) check (discount_value is null or discount_value >= 0),
  draft_payload jsonb not null default '{}'::jsonb,
  subtotal numeric(12, 2) not null default 0,
  final_total numeric(12, 2) not null default 0,
  payment_method text check (payment_method in ('cash', 'gcash')),
  amount_paid numeric(12, 2) check (amount_paid is null or amount_paid >= 0),
  cash_received numeric(12, 2) check (cash_received is null or cash_received >= 0),
  change_due numeric(12, 2) check (change_due is null or change_due >= 0),
  payment_reference text,
  completed_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.sales_service_lines (
  id uuid primary key default gen_random_uuid(),
  sales_transaction_id uuid not null references public.sales_transactions(id) on delete cascade,
  service_id uuid references public.services(id) on delete set null,
  service_name text not null,
  sort_order integer not null default 0,
  subtotal numeric(12, 2) not null default 0,
  final_total numeric(12, 2) not null default 0,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.sales_material_entries (
  id uuid primary key default gen_random_uuid(),
  sales_service_line_id uuid not null references public.sales_service_lines(id) on delete cascade,
  inventory_item_id uuid references public.inventory_items(id) on delete set null,
  material_name text not null,
  quantity numeric(12, 2) not null check (quantity > 0),
  unit_price numeric(12, 2) not null check (unit_price >= 0),
  line_total numeric(12, 2) not null default 0 check (line_total >= 0),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.sales_add_on_entries (
  id uuid primary key default gen_random_uuid(),
  sales_material_entry_id uuid not null references public.sales_material_entries(id) on delete cascade,
  add_on_id uuid references public.add_ons(id) on delete set null,
  add_on_name text not null,
  quantity numeric(12, 2) not null check (quantity > 0),
  unit_price numeric(12, 2) not null check (unit_price >= 0),
  line_total numeric(12, 2) not null default 0 check (line_total >= 0),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.inventory_movements (
  id uuid primary key default gen_random_uuid(),
  inventory_item_id uuid not null references public.inventory_items(id) on delete cascade,
  sales_transaction_id uuid references public.sales_transactions(id) on delete set null,
  sales_material_entry_id uuid references public.sales_material_entries(id) on delete set null,
  movement_type text not null check (movement_type in ('sale_deduction', 'restock', 'manual_adjustment', 'correction')),
  quantity_delta numeric(12, 2) not null,
  note text,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.services enable row level security;
alter table public.add_ons enable row level security;
alter table public.inventory_items enable row level security;
alter table public.service_material_prices enable row level security;
alter table public.sales_transactions enable row level security;
alter table public.sales_service_lines enable row level security;
alter table public.sales_material_entries enable row level security;
alter table public.sales_add_on_entries enable row level security;
alter table public.inventory_movements enable row level security;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists sales_transactions_set_updated_at on public.sales_transactions;

create trigger sales_transactions_set_updated_at
before update on public.sales_transactions
for each row
execute function public.set_updated_at();

create or replace function public.decrement_inventory_item_stock(
  p_inventory_item_id uuid,
  p_quantity numeric,
  p_sales_transaction_id uuid default null,
  p_sales_material_entry_id uuid default null,
  p_note text default null
)
returns public.inventory_movements
language plpgsql
as $$
declare
  v_inventory_item public.inventory_items;
  v_movement public.inventory_movements;
begin
  if p_quantity is null or p_quantity <= 0 then
    raise exception 'Quantity to deduct must be greater than zero.';
  end if;

  update public.inventory_items
  set stock_quantity = stock_quantity - p_quantity
  where id = p_inventory_item_id
    and stock_quantity >= p_quantity
  returning * into v_inventory_item;

  if not found then
    raise exception 'Inventory item not found or insufficient stock.';
  end if;

  insert into public.inventory_movements (
    inventory_item_id,
    sales_transaction_id,
    sales_material_entry_id,
    movement_type,
    quantity_delta,
    note
  )
  values (
    p_inventory_item_id,
    p_sales_transaction_id,
    p_sales_material_entry_id,
    'sale_deduction',
    -p_quantity,
    p_note
  )
  returning * into v_movement;

  return v_movement;
end;
$$;

drop policy if exists "services_all_authenticated" on public.services;
create policy "services_all_authenticated"
on public.services
for all
to authenticated
using (true)
with check (true);

drop policy if exists "add_ons_all_authenticated" on public.add_ons;
create policy "add_ons_all_authenticated"
on public.add_ons
for all
to authenticated
using (true)
with check (true);

drop policy if exists "inventory_items_all_authenticated" on public.inventory_items;
create policy "inventory_items_all_authenticated"
on public.inventory_items
for all
to authenticated
using (true)
with check (true);

drop policy if exists "service_material_prices_all_authenticated" on public.service_material_prices;
create policy "service_material_prices_all_authenticated"
on public.service_material_prices
for all
to authenticated
using (true)
with check (true);

drop policy if exists "sales_transactions_all_authenticated" on public.sales_transactions;
create policy "sales_transactions_all_authenticated"
on public.sales_transactions
for all
to authenticated
using (true)
with check (true);

drop policy if exists "sales_service_lines_all_authenticated" on public.sales_service_lines;
create policy "sales_service_lines_all_authenticated"
on public.sales_service_lines
for all
to authenticated
using (true)
with check (true);

drop policy if exists "sales_material_entries_all_authenticated" on public.sales_material_entries;
create policy "sales_material_entries_all_authenticated"
on public.sales_material_entries
for all
to authenticated
using (true)
with check (true);

drop policy if exists "sales_add_on_entries_all_authenticated" on public.sales_add_on_entries;
create policy "sales_add_on_entries_all_authenticated"
on public.sales_add_on_entries
for all
to authenticated
using (true)
with check (true);

drop policy if exists "inventory_movements_all_authenticated" on public.inventory_movements;
create policy "inventory_movements_all_authenticated"
on public.inventory_movements
for all
to authenticated
using (true)
with check (true);
