create extension if not exists citext;

create table if not exists public.allowed_users (
  id uuid primary key default gen_random_uuid(),
  email citext not null unique,
  role text not null default 'physical_dept'
    check (role in ('owner', 'design_dept', 'physical_dept', 'dev_dept')),
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.allowed_users enable row level security;

drop policy if exists "allowed_users_select_own_email" on public.allowed_users;

create policy "allowed_users_select_own_email"
on public.allowed_users
for select
to authenticated
using (
  lower(email::text) = lower(coalesce((auth.jwt() ->> 'email'), ''))
);

comment on table public.allowed_users is
'Application allowlist for Beyond Ink POS Google-authenticated users with department roles.';

create table if not exists public.service_categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  department text not null default 'physical_dept'
    check (department in ('design_dept', 'physical_dept', 'dev_dept')),
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.services (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  category_id uuid references public.service_categories(id) on delete set null,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.add_ons (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  department text not null default 'physical_dept'
    check (department in ('design_dept', 'physical_dept', 'dev_dept')),
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.inventory_items (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  unit text not null default 'sheet',
  stock_on_hand numeric(12, 2) not null default 0,
  low_stock_threshold numeric(12, 2) not null default 0,
  cost_per_unit numeric(12, 2) not null default 0,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.service_material_prices (
  id uuid primary key default gen_random_uuid(),
  service_id uuid not null references public.services(id) on delete cascade,
  inventory_item_id uuid not null references public.inventory_items(id) on delete restrict,
  suggested_unit_price numeric(12, 2) not null,
  created_at timestamptz not null default timezone('utc', now()),
  unique (service_id, inventory_item_id)
);

create table if not exists public.sales_transactions (
  id uuid primary key default gen_random_uuid(),
  transaction_number bigint generated by default as identity unique,
  status text not null default 'draft' check (status in ('draft', 'completed', 'cancelled')),
  department text not null default 'physical_dept'
    check (department in ('design_dept', 'physical_dept', 'dev_dept')),
  cashier_name text not null,
  delivery_enabled boolean not null default false,
  customer_name text,
  delivery_address text,
  drop_off_location text,
  delivery_fee numeric(12, 2) not null default 0,
  discount_type text check (discount_type in ('fixed', 'percentage')),
  discount_value numeric(12, 2),
  draft_payload jsonb not null default '{}'::jsonb,
  subtotal numeric(12, 2) not null default 0,
  final_total numeric(12, 2) not null default 0,
  payment_method text check (payment_method in ('cash', 'gcash')),
  cash_received numeric(12, 2),
  gcash_amount_paid numeric(12, 2),
  change_due numeric(12, 2),
  completed_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.sales_service_lines (
  id uuid primary key default gen_random_uuid(),
  transaction_id uuid not null references public.sales_transactions(id) on delete cascade,
  service_id uuid not null references public.services(id) on delete restrict,
  service_name text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.sales_material_entries (
  id uuid primary key default gen_random_uuid(),
  service_line_id uuid not null references public.sales_service_lines(id) on delete cascade,
  inventory_item_id uuid not null references public.inventory_items(id) on delete restrict,
  material_name text not null,
  quantity numeric(12, 2) not null,
  unit_price numeric(12, 2) not null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.sales_add_on_entries (
  id uuid primary key default gen_random_uuid(),
  material_entry_id uuid not null references public.sales_material_entries(id) on delete cascade,
  add_on_id uuid not null references public.add_ons(id) on delete restrict,
  add_on_name text not null,
  quantity numeric(12, 2) not null,
  unit_price numeric(12, 2) not null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.inventory_movements (
  id uuid primary key default gen_random_uuid(),
  inventory_item_id uuid not null references public.inventory_items(id) on delete restrict,
  transaction_id uuid references public.sales_transactions(id) on delete set null,
  movement_type text not null check (movement_type in ('sale_deduction', 'manual_adjustment', 'purchase_receipt')),
  quantity_delta numeric(12, 2) not null,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.service_categories enable row level security;
alter table public.services enable row level security;
alter table public.add_ons enable row level security;
alter table public.inventory_items enable row level security;
alter table public.service_material_prices enable row level security;
alter table public.sales_transactions enable row level security;
alter table public.sales_service_lines enable row level security;
alter table public.sales_material_entries enable row level security;
alter table public.sales_add_on_entries enable row level security;
alter table public.inventory_movements enable row level security;

-- ─── Helper functions ──────────────────────────────────────────────

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists sales_transactions_set_updated_at on public.sales_transactions;

create trigger sales_transactions_set_updated_at
before update on public.sales_transactions
for each row
execute function public.set_updated_at();

create or replace function public.decrement_inventory_item_stock(
  inventory_item_id_input uuid,
  quantity_input numeric,
  transaction_id_input uuid
)
returns void
language plpgsql
as $$
begin
  update public.inventory_items
  set stock_on_hand = stock_on_hand - quantity_input
  where id = inventory_item_id_input;

  insert into public.inventory_movements (
    inventory_item_id,
    transaction_id,
    movement_type,
    quantity_delta
  )
  values (
    inventory_item_id_input,
    transaction_id_input,
    'sale_deduction',
    quantity_input * -1
  );
end;
$$;

create or replace function public.get_user_role()
returns text
language sql
stable
security definer
as $$
  select role from public.allowed_users
  where lower(email::text) = lower(coalesce((auth.jwt() ->> 'email'), ''))
  limit 1;
$$;

create or replace function public.is_owner()
returns boolean
language sql
stable
security definer
as $$
  select public.get_user_role() = 'owner';
$$;

-- ─── RLS Policies ─────────────────────────────────────────────────

-- allowed_users: users can read their own row (to get their role)
drop policy if exists "allowed_users_select_own_email" on public.allowed_users;
create policy "allowed_users_select_own_email"
on public.allowed_users
for select
to authenticated
using (
  lower(email::text) = lower(coalesce((auth.jwt() ->> 'email'), ''))
);

-- service_categories: department-scoped read, owner-only write
drop policy if exists "service_categories_all_authenticated" on public.service_categories;

create policy "service_categories_select"
on public.service_categories for select to authenticated
using (public.is_owner() OR department = public.get_user_role());

create policy "service_categories_insert"
on public.service_categories for insert to authenticated
with check (public.is_owner());

create policy "service_categories_update"
on public.service_categories for update to authenticated
using (public.is_owner()) with check (public.is_owner());

create policy "service_categories_delete"
on public.service_categories for delete to authenticated
using (public.is_owner());

-- services: read all (filtered via category.department), owner-only write
drop policy if exists "services_all_authenticated" on public.services;

create policy "services_select"
on public.services for select to authenticated
using (
  public.is_owner() OR EXISTS (
    SELECT 1 FROM public.service_categories sc
    WHERE sc.id = services.category_id
      AND sc.department = public.get_user_role()
  )
);

create policy "services_insert"
on public.services for insert to authenticated
with check (public.is_owner());

create policy "services_update"
on public.services for update to authenticated
using (public.is_owner()) with check (public.is_owner());

create policy "services_delete"
on public.services for delete to authenticated
using (public.is_owner());

-- add_ons: department-scoped read, owner-only write
drop policy if exists "add_ons_all_authenticated" on public.add_ons;

create policy "add_ons_select"
on public.add_ons for select to authenticated
using (public.is_owner() OR department = public.get_user_role());

create policy "add_ons_insert"
on public.add_ons for insert to authenticated
with check (public.is_owner());

create policy "add_ons_update"
on public.add_ons for update to authenticated
using (public.is_owner()) with check (public.is_owner());

create policy "add_ons_delete"
on public.add_ons for delete to authenticated
using (public.is_owner());

-- inventory_items: physical_dept and owner only
drop policy if exists "inventory_items_all_authenticated" on public.inventory_items;

create policy "inventory_items_select"
on public.inventory_items for select to authenticated
using (public.is_owner() OR public.get_user_role() = 'physical_dept');

create policy "inventory_items_insert"
on public.inventory_items for insert to authenticated
with check (public.is_owner());

create policy "inventory_items_update"
on public.inventory_items for update to authenticated
using (public.is_owner()) with check (public.is_owner());

create policy "inventory_items_delete"
on public.inventory_items for delete to authenticated
using (public.is_owner());

-- service_material_prices: all authenticated (no department column, tied to inventory)
drop policy if exists "service_material_prices_all_authenticated" on public.service_material_prices;
create policy "service_material_prices_all_authenticated"
on public.service_material_prices
for all
to authenticated
using (true)
with check (true);

-- sales_transactions: department-scoped
drop policy if exists "sales_transactions_all_authenticated" on public.sales_transactions;

create policy "sales_transactions_select"
on public.sales_transactions for select to authenticated
using (public.is_owner() OR department = public.get_user_role());

create policy "sales_transactions_insert"
on public.sales_transactions for insert to authenticated
with check (public.is_owner() OR department = public.get_user_role());

create policy "sales_transactions_update"
on public.sales_transactions for update to authenticated
using (public.is_owner() OR department = public.get_user_role())
with check (public.is_owner() OR department = public.get_user_role());

create policy "sales_transactions_delete"
on public.sales_transactions for delete to authenticated
using (public.is_owner() OR department = public.get_user_role());

-- sales_service_lines: department-scoped via parent transaction
drop policy if exists "sales_service_lines_all_authenticated" on public.sales_service_lines;

create policy "sales_service_lines_select"
on public.sales_service_lines for select to authenticated
using (EXISTS (
  SELECT 1 FROM public.sales_transactions t
  WHERE t.id = sales_service_lines.transaction_id
    AND (public.is_owner() OR t.department = public.get_user_role())
));

create policy "sales_service_lines_insert"
on public.sales_service_lines for insert to authenticated
with check (EXISTS (
  SELECT 1 FROM public.sales_transactions t
  WHERE t.id = sales_service_lines.transaction_id
    AND (public.is_owner() OR t.department = public.get_user_role())
));

create policy "sales_service_lines_delete"
on public.sales_service_lines for delete to authenticated
using (EXISTS (
  SELECT 1 FROM public.sales_transactions t
  WHERE t.id = sales_service_lines.transaction_id
    AND (public.is_owner() OR t.department = public.get_user_role())
));

-- sales_material_entries: department-scoped via service line → transaction
drop policy if exists "sales_material_entries_all_authenticated" on public.sales_material_entries;

create policy "sales_material_entries_select"
on public.sales_material_entries for select to authenticated
using (EXISTS (
  SELECT 1 FROM public.sales_service_lines sl
  JOIN public.sales_transactions t ON t.id = sl.transaction_id
  WHERE sl.id = sales_material_entries.service_line_id
    AND (public.is_owner() OR t.department = public.get_user_role())
));

create policy "sales_material_entries_insert"
on public.sales_material_entries for insert to authenticated
with check (EXISTS (
  SELECT 1 FROM public.sales_service_lines sl
  JOIN public.sales_transactions t ON t.id = sl.transaction_id
  WHERE sl.id = sales_material_entries.service_line_id
    AND (public.is_owner() OR t.department = public.get_user_role())
));

create policy "sales_material_entries_delete"
on public.sales_material_entries for delete to authenticated
using (EXISTS (
  SELECT 1 FROM public.sales_service_lines sl
  JOIN public.sales_transactions t ON t.id = sl.transaction_id
  WHERE sl.id = sales_material_entries.service_line_id
    AND (public.is_owner() OR t.department = public.get_user_role())
));

-- sales_add_on_entries: department-scoped via material → service line → transaction
drop policy if exists "sales_add_on_entries_all_authenticated" on public.sales_add_on_entries;

create policy "sales_add_on_entries_select"
on public.sales_add_on_entries for select to authenticated
using (EXISTS (
  SELECT 1 FROM public.sales_material_entries me
  JOIN public.sales_service_lines sl ON sl.id = me.service_line_id
  JOIN public.sales_transactions t ON t.id = sl.transaction_id
  WHERE me.id = sales_add_on_entries.material_entry_id
    AND (public.is_owner() OR t.department = public.get_user_role())
));

create policy "sales_add_on_entries_insert"
on public.sales_add_on_entries for insert to authenticated
with check (EXISTS (
  SELECT 1 FROM public.sales_material_entries me
  JOIN public.sales_service_lines sl ON sl.id = me.service_line_id
  JOIN public.sales_transactions t ON t.id = sl.transaction_id
  WHERE me.id = sales_add_on_entries.material_entry_id
    AND (public.is_owner() OR t.department = public.get_user_role())
));

create policy "sales_add_on_entries_delete"
on public.sales_add_on_entries for delete to authenticated
using (EXISTS (
  SELECT 1 FROM public.sales_material_entries me
  JOIN public.sales_service_lines sl ON sl.id = me.service_line_id
  JOIN public.sales_transactions t ON t.id = sl.transaction_id
  WHERE me.id = sales_add_on_entries.material_entry_id
    AND (public.is_owner() OR t.department = public.get_user_role())
));

-- inventory_movements: physical_dept and owner only
drop policy if exists "inventory_movements_all_authenticated" on public.inventory_movements;

create policy "inventory_movements_select"
on public.inventory_movements for select to authenticated
using (public.is_owner() OR public.get_user_role() = 'physical_dept');

create policy "inventory_movements_insert"
on public.inventory_movements for insert to authenticated
with check (public.is_owner() OR public.get_user_role() = 'physical_dept');
